# Generated by Django 5.1.1 on 2025-02-10 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_Number', models.IntegerField()),
                ('taux_Horaire', models.FloatField(blank=True, null=True)),
                ('conge', models.FloatField(blank=True, null=True)),
                ('primes', models.JSONField(blank=True, default=dict, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('heure_pause_debut', models.TimeField(blank=True, null=True)),
                ('heure_pause_fin', models.TimeField(blank=True, null=True)),
                ('jours_travail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_name', models.CharField(max_length=255, unique=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('montant_ttc', models.FloatField(null=True)),
                ('montant_ht', models.FloatField(null=True)),
                ('state_chantier', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_codepostal', message='Le code postal doit être exactement 5 chiffres.', regex='^\\d{5}$')])),
                ('cout_materiel', models.FloatField(null=True)),
                ('cout_main_oeuvre', models.FloatField(null=True)),
                ('cout_sous_traitance', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('client_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Fournisseur_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
                ('description_fournisseur', models.CharField(max_length=250)),
                ('magasin', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LigneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=10)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cout_materiel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_produit', models.CharField(max_length=25)),
                ('description_produit', models.CharField(max_length=250)),
                ('price_ht', models.FloatField()),
                ('name_fournisseur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(default='', max_length=50, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('unite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fournisseur', models.CharField(max_length=100)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente Livraison'), ('livre_chantier', 'Livré Chantier'), ('retrait_magasin', 'Retrait Magasin')], default='en_attente', max_length=20)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('magasin_retrait', models.CharField(blank=True, max_length=200, null=True)),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non Payé'), ('paye', 'Payé'), ('paye_partiel', 'Payé Partiellement')], default='non_paye', max_length=20)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('price_ht', models.FloatField()),
                ('price_ttc', models.FloatField()),
                ('tva_rate', models.FloatField()),
                ('nature_travaux', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('lignes_speciales', models.JSONField(blank=True, default=dict)),
                ('devis_chantier', models.BooleanField(default=False)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='devis', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('hours_modified', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('state_facture', models.CharField(choices=[('En cours', 'En cours'), ('Attente paiement', 'Attente paiement'), ('Payée', 'Payée')], default='En attente', max_length=20)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(default='virement', max_length=50)),
                ('price_ht', models.FloatField()),
                ('price_ttc', models.FloatField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.chantier')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.devis')),
            ],
        ),
        migrations.CreateModel(
            name='FacturePartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='FactureSousPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties', to='api.facturepartie')),
            ],
        ),
        migrations.CreateModel(
            name='FactureLigneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unite', models.CharField(max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.facturesouspartie')),
            ],
        ),
        migrations.CreateModel(
            name='FournisseurMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=100)),
                ('magasin', models.CharField(max_length=200)),
                ('derniere_utilisation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-derniere_utilisation'],
                'unique_together': {('fournisseur', 'magasin')},
            },
        ),
        migrations.CreateModel(
            name='FactureLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.facture')),
                ('ligne_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lignedetail')),
            ],
        ),
        migrations.CreateModel(
            name='DevisLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.devis')),
                ('ligne_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lignedetail')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('days_present', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
            ],
        ),
        migrations.AddField(
            model_name='lignedetail',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.partie'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures_travail', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_quitus', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('description_quitus', models.CharField(max_length=250)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quitus', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='quitus', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='situations', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=25)),
                ('ville_societe', models.CharField(max_length=100)),
                ('rue_societe', models.CharField(max_length=100)),
                ('codepostal_societe', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_codepostal', message='Le code postal doit être exactement 5 chiffres.', regex='^\\d{5}$')])),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='api.societe'),
        ),
        migrations.CreateModel(
            name='SousPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties', to='api.partie')),
            ],
        ),
        migrations.AddField(
            model_name='lignedetail',
            name='sous_partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.souspartie'),
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.boncommande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_operation', models.CharField(choices=[('ajout', 'Ajout'), ('retrait', 'Retrait')], max_length=10)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chantier')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement_type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chantier')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_costs', to='api.agent')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_costs', to='api.chantier')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'week', 'year'], name='api_laborco_agent_i_f1e716_idx'), models.Index(fields=['chantier', 'week', 'year'], name='api_laborco_chantie_62acd2_idx')],
                'unique_together': {('agent', 'chantier', 'week', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_hours', to='api.agent')),
            ],
            options={
                'unique_together': {('agent', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField(default=2025)),
                ('day', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chantier')),
            ],
            options={
                'unique_together': {('agent', 'week', 'year', 'day', 'hour')},
            },
        ),
    ]
