# Generated by Django 5.1.1 on 2025-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantite_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code_produit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('code_produit', 'fournisseur')},
        ),
    ]
