# Generated by Django 5.1.1 on 2025-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'date_modification',
            },
        ),
    ]
