# Generated by Django 5.1.1 on 2024-12-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='chantier_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
