# Generated by Django 5.1.1 on 2025-07-29 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='avenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.avenantsoustraitance'),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.contratsoustraitance'),
        ),
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together={('chantier', 'sous_traitant', 'mois', 'annee', 'avenant')},
        ),
    ]
