# Generated by Django 5.1.1 on 2025-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situation',
            options={'ordering': ['-annee', '-mois']},
        ),
        migrations.AlterUniqueTogether(
            name='situation',
            unique_together={('chantier', 'mois', 'annee')},
        ),
        migrations.AddField(
            model_name='situation',
            name='numero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
