# Generated by Django 5.1.1 on 2025-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='numero',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
