# Generated by Django 5.1.1 on 2025-02-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situation',
            options={'ordering': ['-annee', '-mois']},
        ),
        migrations.AlterUniqueTogether(
            name='situation',
            unique_together={('chantier', 'mois', 'annee')},
        ),
        migrations.AddField(
            model_name='situation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='situation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='devis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.devis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_ht_cumule',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='pourcentage_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='situation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('facturee', 'Facturée')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='situation',
            name='taux_prorata',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='situation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='situation',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='situation',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chantier'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='mois',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='situation',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='situation',
            name='commentaire',
        ),
    ]
