# Generated by Django 5.1.1 on 2024-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chantier_chantier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='chantier_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
