# Generated by Django 5.1.1 on 2025-02-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_situation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChantierLigneSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_supplementaires_default', to='api.chantier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SituationLigneSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(default='deduction', max_length=20)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_supplementaires', to='api.situation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
