# Generated by Django 5.1.1 on 2025-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paiementsoustraitant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='numero_cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CP'),
        ),
    ]
