# Generated by Django 5.1.1 on 2025-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tauxfixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='cout_estime_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Coût estimé main d'œuvre"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='cout_estime_materiel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût estimé matériel'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='marge_estimee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marge estimée'),
        ),
    ]
