# Generated by Django 5.1.1 on 2025-02-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_situation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='cumul_mois_precedent',
            new_name='cumul_precedent',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='montant_total_mois_apres_retenue',
            new_name='montant_apres_retenues',
        ),
    ]
