# Generated by Django 5.1.1 on 2025-08-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_quantite_disponible_alter_stock_code_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='contact_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_contact', to='api.agent'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='contact_sous_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_contact', to='api.soustraitant'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('sous_traitant', 'Sous-traitant')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='date_creation_personnalisee',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création du document'),
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
