# Generated by Django 5.1.1 on 2025-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chantierlignesupplementaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='retenue_cie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
