# Generated by Django 5.1.1 on 2025-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agencyexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyexpense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
