# Generated by Django 5.1.1 on 2025-08-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boncommande_contact_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='emetteur_id',
            field=models.IntegerField(blank=True, help_text="ID statique de l'émetteur (1=Amine, 2=Adel)", null=True),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agent'),
        ),
    ]
