# Generated by Django 5.1.1 on 2024-12-24 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chantier_chantier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='chantier_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_codepostal', message='Le code postal doit être exactement 5 chiffres.', regex='^\\d{5}$')]),
        ),
    ]
