# Generated by Django 5.1.1 on 2025-02-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cumul_mois_precedent_situation_cumul_precedent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationligne',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationligneavenant',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_avenant', to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_supplementaires', to='api.situation'),
        ),
    ]
