# Generated by Django 5.1.1 on 2025-02-11 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parametres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='api.chantier')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('chantier', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='FactureTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ts', models.IntegerField()),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_ts', to='api.avenant')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_ts', to='api.chantier')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture_ts', to='api.devis')),
            ],
            options={
                'ordering': ['numero_ts'],
                'unique_together': {('chantier', 'numero_ts')},
            },
        ),
    ]
