# Generated by Django 5.1.1 on 2025-02-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_situation_retenue_cie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationFactureCIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SituationLigneAvenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_precedent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pourcentage_actuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='situationligne',
            name='one_line_type_only',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='montant_actuel',
            new_name='montant_ht_mois',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='montant_ht_cumule',
            new_name='montant_prorata',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='pourcentage_actuel',
            new_name='pourcentage_avancement',
        ),
        migrations.RemoveField(
            model_name='situationligne',
            name='facture_ts',
        ),
        migrations.RemoveField(
            model_name='situationligne',
            name='pourcentage',
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='retenue_garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situationligne',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligne',
            name='pourcentage_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligne',
            name='pourcentage_precedent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='taux_prorata',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='ligne_devis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.devisligne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='type',
            field=models.CharField(choices=[('deduction', 'Déduction'), ('addition', 'Addition')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='situationligne',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ligne_devis__isnull', False), ('pourcentage_actuel__isnull', False), ('pourcentage_precedent__isnull', False)), models.Q(('ligne_devis__isnull', True), ('pourcentage_actuel__isnull', True), ('pourcentage_precedent__isnull', True)), _connector='OR'), name='one_line_type_only'),
        ),
        migrations.AddField(
            model_name='situationfacturecie',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facture'),
        ),
        migrations.AddField(
            model_name='situationfacturecie',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.situation'),
        ),
        migrations.AddField(
            model_name='situationligneavenant',
            name='facture_ts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facturets'),
        ),
        migrations.AddField(
            model_name='situationligneavenant',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.situation'),
        ),
    ]
