# Generated by Django 5.1.1 on 2025-08-07 13:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banque_situation_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.chantier'),
        ),
        migrations.CreateModel(
            name='AppelOffres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_name', models.CharField(max_length=255, unique=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('montant_ttc', models.FloatField(null=True)),
                ('montant_ht', models.FloatField(null=True)),
                ('state_chantier', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_codepostal', message='Le code postal doit être exactement 5 chiffres.', regex='^\\d{5}$')])),
                ('cout_materiel', models.FloatField(null=True)),
                ('cout_main_oeuvre', models.FloatField(null=True)),
                ('cout_sous_traitance', models.FloatField(null=True)),
                ('cout_estime_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Coût estimé main d'œuvre")),
                ('cout_estime_materiel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût estimé matériel')),
                ('marge_estimee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marge estimée')),
                ('description', models.TextField(null=True)),
                ('taux_fixe', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente validation'), ('refuse', 'Refusé'), ('valide', 'Validé')], default='en_attente', max_length=20, verbose_name="Statut de l'appel d'offres")),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('raison_refus', models.TextField(blank=True, null=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='api.societe')),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='appel_offres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.appeloffres'),
        ),
    ]
