# Generated by Django 5.1.1 on 2025-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boncommande_emetteur_id_alter_boncommande_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='contact_entreprise',
            field=models.CharField(blank=True, help_text='Entreprise du contact (pour sous-traitant)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='contact_nom',
            field=models.CharField(blank=True, help_text='Nom du contact réceptionnaire', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Téléphone du contact', max_length=20, null=True),
        ),
    ]
