# Generated by Django 5.1.1 on 2025-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_situationligne_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='montant_total_devis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_total_travaux',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='total_avancement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
