# Generated by Django 5.1.1 on 2025-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boncommande_date_creation_alter_ligneboncommande_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente Livraison'), ('livre_chantier', 'Livré Chantier'), ('retrait_magasin', 'Retrait Magasin')], default='en_attente', max_length=20),
        ),
    ]
