# Generated by Django 5.1.1 on 2025-02-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agencyexpense_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyExpenseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='api.agencyexpense')),
            ],
            options={
                'unique_together': {('expense', 'month', 'year')},
            },
        ),
    ]
