# Generated by Django 5.1.1 on 2024-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chantier_chantier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='nature_travaux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
