# Generated by Django 5.1.1 on 2024-12-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devis_nature_travaux_devis_tva_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=10)),
                ('type', models.CharField(choices=[('reduction', 'Réduction'), ('addition', 'Addition')], max_length=10)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('global', 'Global'), ('partie', 'Partie'), ('sous_partie', 'Sous-partie')], max_length=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales', to='api.devis')),
                ('partie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.partie')),
                ('sous_partie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.souspartie')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
