# Generated by Django 5.1.1 on 2025-02-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_avenant_facturets'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.avenant'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('classique', 'Classique'), ('ts', 'Travaux Supplémentaires')], default='classique', max_length=20),
        ),
    ]
