# Generated by Django 5.1.1 on 2025-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boncommande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=100)),
                ('magasin', models.CharField(max_length=200)),
                ('derniere_utilisation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-derniere_utilisation'],
                'unique_together': {('fournisseur', 'magasin')},
            },
        ),
    ]
