# Generated by Django 5.1.1 on 2025-02-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_situationfacturecie_situationligneavenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='situationligne',
            name='one_line_type_only',
        ),
        migrations.RemoveField(
            model_name='situationlignesupplementaire',
            name='type',
        ),
        migrations.AddField(
            model_name='situationligne',
            name='facture_ts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.facturets'),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='ligne_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.devisligne'),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='pourcentage_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='pourcentage_precedent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_lignes', to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationligneavenant',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_lignes_avenant', to='api.situation'),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_lignes_supplementaires', to='api.situation'),
        ),
    ]
