# Generated by Django 5.2.dev20240702005204 on 2024-10-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='produit',
            new_name='stock',
        ),
    ]
