# Generated by Django 5.1.1 on 2025-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boncommande_contact_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='contact_entreprise',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='contact_nom',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='contact_telephone',
        ),
    ]
