# Generated by Django 5.1.1 on 2025-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_devis_chantier_appeloffres_devis_appel_offres'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyExpenseAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totals_by_category', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month'],
                'indexes': [models.Index(fields=['year', 'month'], name='api_agencye_year_a94087_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
