# Generated by Django 5.1.1 on 2025-02-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agencyexpenseoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=255)),
                ('siege_social', models.CharField(max_length=255)),
                ('forme_juridique', models.CharField(max_length=100)),
                ('numero_rcs', models.CharField(max_length=100, unique=True)),
                ('representant', models.CharField(max_length=255)),
                ('qualite_representant', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituationDateEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('situation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.situation')),
            ],
        ),
        migrations.CreateModel(
            name='ContratSousTraitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=255, unique=True)),
                ('date_contrat', models.DateField()),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_avenant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('designation', models.TextField()),
                ('type_travaux', models.CharField(max_length=255)),
                ('numero_avenant', models.IntegerField(blank=True, null=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_sous_traitance', to='api.chantier')),
                ('sous_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='api.soustraitant')),
            ],
            options={
                'ordering': ['date_contrat', 'numero_avenant'],
                'unique_together': {('chantier', 'sous_traitant', 'numero_avenant')},
            },
        ),
    ]
