# Generated by Django 5.2.dev20240702005204 on 2024-10-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_produit_stockhistory_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantite_entree',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantite_sortie',
        ),
    ]
