# Generated by Django 5.1.1 on 2025-08-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_agencyexpenseaggregate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('devis', 'Devis'), ('factures', 'Factures'), ('photos', 'Photos'), ('documents', 'Documents'), ('contrats', 'Contrats'), ('autres', 'Autres')], default='documents', max_length=20)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.chantier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.societe')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['societe', 'chantier', 'category'], name='api_documen_societe_01dd75_idx'), models.Index(fields=['owner'], name='api_documen_owner_i_8e6c0a_idx'), models.Index(fields=['created_at'], name='api_documen_created_2fddfd_idx'), models.Index(fields=['is_deleted'], name='api_documen_is_dele_754a77_idx')],
            },
        ),
    ]
