# Generated by Django 5.1.1 on 2025-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_situationligne_one_line_type_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationligne',
            name='facture_ts',
        ),
        migrations.AddField(
            model_name='situationligne',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligne',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligne',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='pourcentage_actuel',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
