# Generated by Django 5.1.1 on 2025-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_facture_avenant_facture_type_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
