# Generated by Django 5.1.1 on 2025-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fournisseurmagasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='magasin_retrait',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
