# Generated by Django 5.1.1 on 2024-12-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lignespeciale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='amount_facturé',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='num_bon_commande',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='num_facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='adresse_facturation',
            field=models.TextField(default='aucune adresse de facturation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='devis_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='api.devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.chantier'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
