# Generated by Django 5.1.1 on 2025-08-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_boncommande_contact_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emetteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_Number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Émetteur',
                'verbose_name_plural': 'Émetteurs',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='emetteur_id',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='emetteur',
            field=models.ForeignKey(blank=True, help_text='Émetteur du bon de commande', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.emetteur'),
        ),
    ]
