# Generated by Django 5.1.1 on 2025-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_soustraitant_situationdateenvoi_contratsoustraitance'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='date_envoi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='date_paiement_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='delai_paiement',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_reel_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
