# Generated by Django 5.1.1 on 2024-12-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_facture_amount_facturé_remove_facture_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.facture')),
                ('ligne_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lignedetail')),
            ],
        ),
        migrations.CreateModel(
            name='FactureSpecialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_type', models.CharField(choices=[('fixed', 'Fixe'), ('percentage', 'Pourcentage')], max_length=20)),
                ('type', models.CharField(choices=[('reduction', 'Réduction'), ('addition', 'Addition')], max_length=20)),
                ('niveau', models.CharField(choices=[('global', 'Global'), ('partie', 'Partie'), ('sous_partie', 'Sous-partie')], max_length=20)),
                ('partie_id', models.IntegerField(blank=True, null=True)),
                ('sous_partie_id', models.IntegerField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facture')),
            ],
        ),
    ]
