# Generated by Django 5.1.1 on 2025-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_situation_date_envoi_situation_date_paiement_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_commande',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
