# Generated by Django 5.1.1 on 2025-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lignes_display',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
