# Generated by Django 5.1.1 on 2025-08-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emetteur_remove_boncommande_emetteur_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='emetteur',
            field=models.ForeignKey(help_text='Émetteur du bon de commande', on_delete=django.db.models.deletion.PROTECT, to='api.emetteur'),
        ),
    ]
