# Generated by Django 5.1.1 on 2025-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boncommande_date_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='conge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='taux_Horaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
