# Generated by Django 5.1.1 on 2025-02-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_facture_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='annee_situation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='mois_situation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('classique', 'Classique'), ('ts', 'Travaux Supplémentaires'), ('cie', 'CIE')], default='classique', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annee_situation__isnull', False), ('mois_situation__isnull', False), ('type_facture', 'cie')), models.Q(('type_facture', 'cie'), _negated=True), _connector='OR'), name='cie_requires_situation_date'),
        ),
    ]
