# Generated by Django 5.1.1 on 2025-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_situationligne_facture_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationlignesupplementaire',
            name='type',
            field=models.CharField(choices=[('deduction', 'Déduction'), ('ajout', 'Ajout')], default='deduction', max_length=20),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
