# Generated by Django 5.1.1 on 2025-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devis_lignes_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementsoustraitant',
            options={'ordering': ['chantier', 'sous_traitant', 'date_paiement'], 'verbose_name': 'Paiement Sous-Traitant', 'verbose_name_plural': 'Paiements Sous-Traitants'},
        ),
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementsoustraitant',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='delai_paiement',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='mois',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='montant_facture_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together={('chantier', 'sous_traitant', 'date_paiement')},
        ),
    ]
