# Generated by Django 5.1.1 on 2025-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_situationlignesupplementaire_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='cumul_mois_precedent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_total_cumul_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='montant_total_mois_apres_retenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='situation',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
