# Generated by Django 5.1.1 on 2025-05-21 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_boncommande_date_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratsoustraitance',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='contratsoustraitance',
            old_name='type_travaux',
            new_name='adresse_prestation',
        ),
        migrations.RenameField(
            model_name='contratsoustraitance',
            old_name='date_contrat',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='contratsoustraitance',
            old_name='designation',
            new_name='description_prestation',
        ),
        migrations.RenameField(
            model_name='contratsoustraitance',
            old_name='montant_final',
            new_name='montant_operation',
        ),
        migrations.RenameField(
            model_name='soustraitant',
            old_name='siege_social',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='soustraitant',
            old_name='forme_juridique',
            new_name='ville',
        ),
        migrations.AlterUniqueTogether(
            name='contratsoustraitance',
            unique_together={('chantier', 'sous_traitant')},
        ),
        migrations.RemoveField(
            model_name='soustraitant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='soustraitant',
            name='qualite_representant',
        ),
        migrations.AddField(
            model_name='contratsoustraitance',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratsoustraitance',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contratsoustraitance',
            name='duree',
            field=models.CharField(default="Jusqu'à livraison du chantier", max_length=100),
        ),
        migrations.AddField(
            model_name='contratsoustraitance',
            name='nom_operation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='code_postal',
            field=models.CharField(default=13015, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='state_facture',
            field=models.CharField(choices=[('En cours', 'En cours'), ('En attente', 'En attente'), ('Attente paiement', 'Attente paiement'), ('Payée', 'Payée')], default='En attente', max_length=20),
        ),
        migrations.RemoveField(
            model_name='contratsoustraitance',
            name='montant_avenant',
        ),
        migrations.RemoveField(
            model_name='contratsoustraitance',
            name='numero_avenant',
        ),
        migrations.RemoveField(
            model_name='contratsoustraitance',
            name='numero_contrat',
        ),
        migrations.CreateModel(
            name='AvenantSousTraitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='api.contratsoustraitance')),
            ],
            options={
                'ordering': ['-date_creation'],
                'unique_together': {('contrat', 'numero')},
            },
        ),
    ]
