# Generated by Django 5.1.1 on 2024-12-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_factureligne_facturespecialline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturePartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='FactureSousPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties', to='api.facturepartie')),
            ],
        ),
        migrations.CreateModel(
            name='FactureLigneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unite', models.CharField(max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.facturesouspartie')),
            ],
        ),
    ]
