# Generated by Django 5.1.1 on 2025-08-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_boncommande_emetteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='emetteur',
            field=models.ForeignKey(blank=True, help_text='Émetteur du bon de commande', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.emetteur'),
        ),
    ]
