# Generated by Django 5.1.1 on 2024-10-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stock_date_entree_stock_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.chantier'),
        ),
    ]
