# Generated by Django 5.1.1 on 2024-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_presence_chantier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='agent',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='jours_travail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
