# Generated by Django 5.1.1 on 2025-02-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_situation_cumul_mois_precedent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situationligneavenant',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='situationligneavenant',
            name='avenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.avenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligneavenant',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situationligneavenant',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situationligneavenant',
            name='pourcentage_precedent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='situationligneavenant',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_lignes_avenants', to='api.situation'),
        ),
    ]
