# Generated by Django 5.1.1 on 2025-02-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_agent_address_alter_agent_conge_and_more'),
        ('api', '0009_add_default_agents'),
    ]

    operations = [
    ]
