# Generated by Django 5.1.1 on 2024-12-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_facturepartie_facturesouspartie_facturelignedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureligne',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.facture'),
        ),
    ]
