# Generated by Django 5.1.1 on 2025-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_contratsoustraitance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratsoustraitance',
            name='type_contrat',
            field=models.CharField(choices=[('BTP', 'BTP'), ('NETTOYAGE', 'Nettoyage')], default='NETTOYAGE', max_length=20),
        ),
    ]
