# Generated by Django 5.1.1 on 2024-12-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_factureligne_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='lignes',
            field=models.ManyToManyField(through='api.FactureLigne', to='api.lignedetail'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='adresse_facturation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facture',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chantier'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devis_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.devis'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facture',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='price_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='state_facture',
            field=models.CharField(default='En Cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='factureligne',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facture'),
        ),
        migrations.AlterField(
            model_name='factureligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
