# Generated by Django 5.1.1 on 2025-05-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contratsoustraitance_type_contrat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avenantsoustraitance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='avenantsoustraitance',
            name='numero',
        ),
    ]
