# Generated by Django 5.1.1 on 2025-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20250208_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non Payé'), ('paye', 'Payé'), ('paye_partiel', 'Payé Partiellement')], default='non_paye', max_length=20),
        ),
    ]
