# Generated by Django 5.1.1 on 2024-10-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_adress_agent_address_agent_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='heure_pause_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='heure_pause_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
