# Generated by Django 5.1.1 on 2025-08-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_situationlignespeciale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SituationLigneSpeciale',
        ),
    ]
