# Generated by Django 5.1.1 on 2025-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_paiement_global_system'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together={('chantier', 'sous_traitant', 'date_paiement', 'avenant')},
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='type',
            field=models.CharField(blank=True, choices=[('NETTOYAGE', 'Nettoyage'), ('BTP', 'BTP'), ('TCE', 'TCE'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name="Type d'activité"),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='date_paiement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='delai_paiement',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='paiementsoustraitant',
            name='montant_facture_ht',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='paiementsoustraitant',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='paiementsoustraitant',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='paiementsoustraitant',
            name='date_modification',
        ),
    ]
