# Generated by Django 5.1.1 on 2025-02-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_situationligneavenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationligneavenant',
            name='description',
        ),
    ]
