# Generated by Django 5.1.1 on 2025-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_boncommande_date_paiement_boncommande_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='primes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
