# Generated by Django 5.1.1 on 2025-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_avenantsoustraitance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenantsoustraitance',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='avenantsoustraitance',
            unique_together={('contrat', 'numero')},
        ),
    ]
