# Generated by Django 5.1.1 on 2025-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_paiementsoustraitant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenantsoustraitance',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name="Date de création de l'avenant"),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création du contrat'),
        ),
    ]
