# Generated by Django 5.1.1 on 2025-08-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_situationlignespeciale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationLigneSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_type', models.CharField(choices=[('fixed', 'Montant fixe'), ('percentage', 'Pourcentage')], default='fixed', max_length=20)),
                ('type', models.CharField(choices=[('reduction', 'Réduction'), ('ajout', 'Ajout')], default='reduction', max_length=20)),
                ('niveau', models.CharField(choices=[('global', 'Global'), ('partie', 'Partie'), ('sous_partie', 'Sous-partie')], default='global', max_length=20)),
                ('partie_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sous_partie_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pourcentage_precedent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pourcentage_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales', to='api.situation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
