# Generated by Django 5.1.1 on 2024-12-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_facture_lignes_alter_facture_adresse_facturation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureligne',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factureligne',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.facture'),
        ),
        migrations.AlterField(
            model_name='factureligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
