# Generated by Django 5.1.1 on 2025-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_avenantsoustraitance_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenantsoustraitance',
            name='date_creation',
            field=models.DateField(verbose_name="Date de création de l'avenant"),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='date_creation',
            field=models.DateField(verbose_name='Date de création du contrat'),
        ),
    ]
