# Generated by Django 5.1.1 on 2025-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_avenantsoustraitance_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratsoustraitance',
            name='nom_maitre_oeuvre',
            field=models.CharField(default='SSCV TPLD', max_length=255, verbose_name="Nom du maître d'œuvre"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratsoustraitance',
            name='nom_maitre_ouvrage',
            field=models.CharField(default='IN SIDE', max_length=255, verbose_name="Nom du maître d'ouvrage"),
            preserve_default=False,
        ),
    ]
