# Generated by Django 5.1.1 on 2024-10-22 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_hours', to='api.agent')),
            ],
            options={
                'unique_together': {('agent', 'month')},
            },
        ),
    ]
