# Generated by Django 5.1.1 on 2025-01-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_factureligne_total_ht_alter_factureligne_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedetail',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.partie'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
