# Generated by Django 5.1.1 on 2025-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_situationlignespeciale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationlignespeciale',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
