# Generated by Django 5.1.1 on 2025-01-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_lignedetail_partie_alter_schedule_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devisligne',
            unique_together=set(),
        ),
    ]
