# Generated by Django 5.1.1 on 2025-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_avenantsoustraitance_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='type',
            field=models.CharField(choices=[('PEINTURE', 'Peinture'), ('FACADE', 'Façade'), ('TCE', 'TCE')], default='PEINTURE', help_text="Domaine d'activité de la partie", max_length=20),
        ),
    ]
