# Generated by Django 5.1.1 on 2025-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_situationlignespeciale_montant_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationlignespeciale',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
