# Generated by Django 5.1.1 on 2025-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contratsoustraitance_nom_maitre_oeuvre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustraitant',
            name='forme_juridique',
            field=models.CharField(default='SARL', max_length=100),
        ),
    ]
