# Generated by Django 5.1.1 on 2025-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_soustraitant_forme_juridique'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustraitant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
