# Generated by Django 5.1.1 on 2025-08-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_partie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souspartie',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
