# Generated by Django 5.1.1 on 2025-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_situationlignespeciale_montant_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soustraitant',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='forme_juridique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
