# Generated by Django 5.1.1 on 2025-01-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_devisligne_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignespeciale',
            name='ligne_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales', to='api.lignedetail'),
        ),
        migrations.AlterField(
            model_name='lignespeciale',
            name='niveau',
            field=models.CharField(choices=[('global', 'Global'), ('partie', 'Partie'), ('sous_partie', 'Sous-partie'), ('ligne_detail', 'Ligne détail')], max_length=12),
        ),
        migrations.AlterField(
            model_name='lignespeciale',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales', to='api.partie'),
        ),
        migrations.AlterField(
            model_name='lignespeciale',
            name='sous_partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales', to='api.souspartie'),
        ),
    ]
