# Generated by Django 5.1.1 on 2025-08-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_soustraitant_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('numero_facture', models.CharField(max_length=50)),
                ('montant_facture_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_reception', models.DateField()),
                ('delai_paiement', models.IntegerField(choices=[(45, '45 jours'), (60, '60 jours')], default=45)),
                ('date_paiement_prevue', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.avenantsoustraitance')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_sous_traitant', to='api.chantier')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.contratsoustraitance')),
                ('sous_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.soustraitant')),
            ],
            options={
                'verbose_name': 'Facture Sous-Traitant',
                'verbose_name_plural': 'Factures Sous-Traitants',
                'ordering': ['chantier', 'sous_traitant', 'annee', 'mois', 'numero_facture'],
                'unique_together': {('chantier', 'sous_traitant', 'numero_facture', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='PaiementFactureSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement_reel', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.facturesoustraitant')),
            ],
            options={
                'verbose_name': 'Paiement Facture Sous-Traitant',
                'verbose_name_plural': 'Paiements Factures Sous-Traitants',
                'ordering': ['facture', 'date_paiement_reel'],
            },
        ),
    ]
