# Generated by Django 5.1.1 on 2024-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('agent', 'week', 'year', 'day', 'hour')},
        ),
    ]
