# Generated by Django 5.1.1 on 2025-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_soustraitant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenantsoustraitance',
            name='type_travaux',
            field=models.CharField(default='LOT PEINTURE', max_length=100),
        ),
    ]
