# Generated by Django 5.1.1 on 2025-01-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_lignespeciale_ligne_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignespeciale',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='lignespeciale',
            name='ligne_detail',
        ),
        migrations.RemoveField(
            model_name='lignespeciale',
            name='partie',
        ),
        migrations.RemoveField(
            model_name='lignespeciale',
            name='sous_partie',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='adresse_facturation',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_echeance',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='devis_origine',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='lignes',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='numero_facture',
        ),
        migrations.AddField(
            model_name='devis',
            name='lignes_speciales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.devis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='lignes_speciales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='nature_travaux',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='state_facture',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='FactureSpecialLine',
        ),
        migrations.DeleteModel(
            name='LigneSpeciale',
        ),
    ]
