# Generated by Django 5.1.1 on 2024-11-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_schedule_unique_together_schedule_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chantier'),
        ),
    ]
