# Generated by Django 5.1.1 on 2025-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_facturesoustraitant_paiementfacturesoustraitant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturesoustraitant',
            unique_together={('chantier', 'sous_traitant', 'annee', 'mois', 'numero_facture')},
        ),
        migrations.AlterField(
            model_name='facturesoustraitant',
            name='delai_paiement',
            field=models.IntegerField(default=45),
        ),
        migrations.RemoveField(
            model_name='facturesoustraitant',
            name='avenant',
        ),
        migrations.RemoveField(
            model_name='facturesoustraitant',
            name='contrat',
        ),
    ]
