# Generated by Django 5.1.1 on 2025-02-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_lignespeciale_devis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='devis_chantier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devis',
            name='chantier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.chantier'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='devis', to='api.client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='nature_travaux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='price_ht',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='price_ttc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='tva_rate',
            field=models.FloatField(),
        ),
    ]
