# Generated by Django 5.1.1 on 2025-06-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_avenantsoustraitance_type_travaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant_facture_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_envoi_facture', models.DateField(blank=True, null=True)),
                ('delai_paiement', models.IntegerField(default=45)),
                ('montant_paye_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_paiement_reel', models.DateField(blank=True, null=True)),
                ('avenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='api.avenantsoustraitance')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_sous_traitant', to='api.chantier')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='api.contratsoustraitance')),
                ('sous_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.soustraitant')),
            ],
            options={
                'verbose_name': 'Paiement Sous-Traitant',
                'verbose_name_plural': 'Paiements Sous-Traitants',
                'ordering': ['chantier', 'sous_traitant', 'annee', 'mois'],
                'unique_together': {('chantier', 'sous_traitant', 'mois', 'annee', 'contrat', 'avenant')},
            },
        ),
    ]
