# Generated by Django 5.1.1 on 2025-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_paiementsoustraitant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiementsoustraitant',
            unique_together={('chantier', 'sous_traitant', 'mois', 'annee')},
        ),
        migrations.RemoveField(
            model_name='paiementsoustraitant',
            name='avenant',
        ),
        migrations.RemoveField(
            model_name='paiementsoustraitant',
            name='contrat',
        ),
    ]
