# Generated by Django 5.1.1 on 2025-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_devis_devis_chantier_alter_devis_chantier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='lignes_speciales',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='price_ttc',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='tva_rate',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(default='virement', max_length=50),
        ),
    ]
