# Generated by Django 5.1.1 on 2024-11-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_event_chantier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chantier')),
            ],
            options={
                'unique_together': {('agent', 'chantier', 'week', 'year')},
            },
        ),
    ]
