# Generated by Django 5.1.1 on 2025-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_facturesoustraitant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesoustraitant',
            name='date_paiement_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
