# Generated by Django 5.1.1 on 2024-11-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_laborcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborcost',
            name='created_at',
        ),
    ]
