# Generated by Django 5.1.1 on 2025-02-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_facture_lignes_speciales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='chantier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.chantier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='price_ht',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='price_ttc',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
