# Generated by Django 5.1.1 on 2025-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_facturesoustraitant_date_paiement_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='taux_journalier',
            field=models.FloatField(blank=True, help_text='Taux pour une journée complète (agents journaliers)', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='type_paiement',
            field=models.CharField(choices=[('horaire', 'Horaire'), ('journalier', 'Journalier')], default='horaire', max_length=20),
        ),
    ]
