# Generated by Django 5.1.1 on 2025-07-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_paiementsoustraitant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseurMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=255)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_materiel', to='api.chantier')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur Matériel',
                'verbose_name_plural': 'Paiements Fournisseurs Matériel',
                'unique_together': {('chantier', 'fournisseur', 'mois', 'annee')},
            },
        ),
    ]
