# Generated by Django 5.1.1 on 2025-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_facture_chantier_facture_price_ht_facture_price_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='state_facture',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Attente paiement', 'Attente paiement'), ('Payée', 'Payée')], default='En attente', max_length=20),
        ),
    ]
