# Generated by Django 5.1.1 on 2025-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agent_taux_journalier_agent_type_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_sav',
            field=models.BooleanField(default=False),
        ),
    ]
