# Generated by Django 5.1.1 on 2025-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_schedule_is_sav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='type',
            field=models.CharField(default='PEINTURE', help_text="Domaine d'activité de la partie (chaîne libre)", max_length=50),
        ),
    ]
