# Generated by Django 5.1.1 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_boncommande_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='fournisseur',
            field=models.CharField(max_length=100),
        ),
    ]
