# Generated by Django 5.1.1 on 2025-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_facture_date_paiement_alter_facture_state_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
