# Generated by Django 5.1.1 on 2025-07-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_boncommande_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fournisseur'),
        ),
    ]
