# Generated by Django 5.1.1 on 2025-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_partie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_envoi',
            field=models.DateField(blank=True, help_text="Date d'envoi de la facture", null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='delai_paiement',
            field=models.IntegerField(blank=True, help_text='Délai de paiement en jours', null=True),
        ),
    ]
