# Generated by Django 5.1.1 on 2025-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_facture_date_envoi_facture_delai_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedetail',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
