# Generated by Django 5.1.1 on 2025-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_boncommande_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='Fournisseur_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='description_fournisseur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='magasin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
