# Generated by Django 5.1.1 on 2025-07-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_fournisseur_fournisseur_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.fournisseur'),
            preserve_default=False,
        ),
    ]
