# Generated by Django 5.1.1 on 2025-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_lignedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partie',
            name='titre',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom_societe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='souspartie',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
