# Generated by Django 5.1.1 on 2025-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_client_name_alter_partie_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedetail',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='partie',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='souspartie',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='situationligne',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='situationlignespeciale',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='situationlignesupplementaire',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
