# Generated by Django 5.1.1 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_lignedetail_is_deleted_partie_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lignedetail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sous_partie', 'description', 'unite'), name='unique_ligne_detail_active'),
        ),
        migrations.AddConstraint(
            model_name='partie',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('titre', 'type'), name='unique_partie_active'),
        ),
        migrations.AddConstraint(
            model_name='souspartie',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('partie', 'description'), name='unique_sous_partie_active'),
        ),
    ]
