# Generated by Django 5.1.1 on 2025-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_stock_unite_stock_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AddField(
            model_name='stock',
            name='unite',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='fournisseur',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='Fournisseur_mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='description_fournisseur',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='magasin',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone_Number',
            field=models.IntegerField(default='0656773227'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='code_produit',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prix_unitaire',
            field=models.FloatField(default=0),
        ),
    ]
