# Generated by Django 5.1.1 on 2025-07-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_stock_description_stock_unite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.fournisseur'),
        ),
    ]
