# Generated by Django 5.1.1 on 2025-10-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_lignedetail_unique_ligne_detail_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='cout_estime_main_oeuvre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Coût estimé main d'œuvre"),
        ),
        migrations.AddField(
            model_name='devis',
            name='cout_estime_materiel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Coût estimé matériel'),
        ),
        migrations.AddField(
            model_name='facture',
            name='cout_estime_main_oeuvre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Coût estimé main d'œuvre"),
        ),
        migrations.AddField(
            model_name='facture',
            name='cout_estime_materiel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Coût estimé matériel'),
        ),
    ]
