# Generated by Django 5.1.1 on 2025-10-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_devis_cout_estime_main_oeuvre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyexpense',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agent'),
        ),
        migrations.AddField(
            model_name='agencyexpense',
            name='ecole_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyexpense',
            name='is_ecole_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chantier',
            name='chantier_type',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='chantier',
            name='is_system_chantier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('presence', 'Présence'), ('absence', 'Absence'), ('conge', 'Congé'), ('modification_horaire', 'Horaire Modifié'), ('ecole', 'École')], default='absence', max_length=30),
        ),
    ]
