# Generated by Django 5.1.1 on 2025-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_fournisseur_fournisseur_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
