# Generated by Django 5.1.1 on 2025-10-08 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_agencyexpense_agent_agencyexpense_ecole_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type_affectation', models.CharField(choices=[('agence', 'Agence'), ('chantier', 'Chantier')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes_agent', to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primes_chantier', to='api.chantier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prime Agent',
                'verbose_name_plural': 'Primes Agents',
                'ordering': ['-annee', '-mois', 'agent'],
                'indexes': [models.Index(fields=['agent', 'mois', 'annee'], name='api_agentpr_agent_i_7ed35b_idx'), models.Index(fields=['chantier', 'mois', 'annee'], name='api_agentpr_chantie_9a79f1_idx')],
            },
        ),
    ]
