# Generated by Django 5.1.1 on 2025-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_fournisseur_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='taux_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tauxfixe',
            name='annee',
            field=models.PositiveIntegerField(default=2025, unique=True),
            preserve_default=False,
        ),
    ]
