# Generated by Django 5.1.1 on 2025-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_agentprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='type_retenue_cie',
            field=models.CharField(choices=[('deduction', 'Déduction'), ('ajout', 'Ajout')], default='deduction', max_length=20, verbose_name='Type de retenue CIE'),
        ),
    ]
