# Generated by Django 5.1.1 on 2025-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_chantier_taux_fixe_tauxfixe_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='taux_fixe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
