# Generated by Django 5.1.1 on 2025-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_situation_type_retenue_cie'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='taux_retenue_garantie',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux retenue de garantie (%)'),
        ),
    ]
