# Generated by Django 5.1.1 on 2025-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_chantier_taux_fixe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('presence', 'Présence'), ('absence', 'Absence'), ('conge', 'Congé'), ('modification_horaire', 'Horaire Modifié')], default='absence', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='subtype',
            field=models.CharField(blank=True, choices=[('justifiee', 'Justifiée'), ('injustifiee', 'Injustifiée'), ('maladie', 'Maladie'), ('rtt', 'RTT'), ('paye', 'Payé'), ('sans_solde', 'Sans solde'), ('parental', 'Parental'), ('maternite', 'Maternité'), ('paternite', 'Paternité'), (None, 'Aucun')], max_length=30, null=True),
        ),
    ]
