# Generated by Django 5.1.1 on 2025-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_situation_taux_retenue_garantie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='civilite',
            field=models.CharField(blank=True, choices=[('', ''), ('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='', max_length=10, verbose_name='Civilité'),
        ),
    ]
