# Generated by Django 5.1.1 on 2025-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_event_status_event_event_type_event_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborcost',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='laborcost',
            name='hours',
        ),
        migrations.AddField(
            model_name='laborcost',
            name='cost_dimanche',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût des heures dimanche (majoration)', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='cost_ferie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût des heures férié (majoration)', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='cost_normal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût des heures normales', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='cost_samedi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût des heures samedi (majoration)', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='details_majoration',
            field=models.JSONField(blank=True, default=list, help_text='Détail des jours avec majoration (samedi, dimanche, férié)'),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='hours_dimanche',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures effectuées le dimanche', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='hours_ferie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures effectuées les jours fériés', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='hours_normal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures normales (hors samedi/dimanche/férié)', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='hours_samedi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures effectuées le samedi', max_digits=10),
        ),
    ]
