# Generated by Django 5.1.1 on 2025-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_client_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='poste',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Poste'),
        ),
    ]
