# Generated by Django 5.1.1 on 2025-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_client_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
    ]
