# Generated by Django 5.1.1 on 2025-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_overtime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_desactivation',
            field=models.DateField(blank=True, help_text="Date de retrait de l'effectif", null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Agent actif dans l'effectif"),
        ),
    ]
