# Generated by Django 5.1.1 on 2025-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_agent_date_desactivation_agent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesoustraitant',
            name='montant_retenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
