# Generated by Django 5.1.1 on 2025-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_montant_retenue_to_facture_sous_traitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='parties_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
