# Generated by Django 5.1.1 on 2025-10-31 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_devis_parties_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lignes_speciales_v2',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Lignes spéciales v2'),
        ),
        migrations.AddField(
            model_name='devis',
            name='version_systeme_lignes',
            field=models.IntegerField(choices=[(1, 'Ancien'), (2, 'Nouveau')], default=1, verbose_name='Version système lignes spéciales'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la couleur')),
                ('hex_value', models.CharField(max_length=7, verbose_name='Valeur hexadécimale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
