# Generated by Django 5.1.1 on 2025-11-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_devis_lignes_speciales_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedetail',
            name='devis',
            field=models.ForeignKey(blank=True, help_text='Lien vers devis pour système unifié (null = catalogue)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details_unifiees', to='api.devis'),
        ),
        migrations.AddField(
            model_name='lignedetail',
            name='index_global',
            field=models.IntegerField(blank=True, default=0, help_text='Position dans le devis (0 = catalogue, >0 = système unifié)'),
        ),
        migrations.AddField(
            model_name='lignedetail',
            name='numero',
            field=models.CharField(blank=True, help_text="Numéro auto-généré: '1.1.1', '1.1.2', etc.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lignedetail',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Quantité pour système unifié', max_digits=10),
        ),
        migrations.AddField(
            model_name='partie',
            name='devis',
            field=models.ForeignKey(blank=True, help_text='Lien vers devis pour système unifié (null = catalogue)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_unifiees', to='api.devis'),
        ),
        migrations.AddField(
            model_name='partie',
            name='index_global',
            field=models.IntegerField(blank=True, default=0, help_text='Position dans le devis (0 = catalogue, >0 = système unifié)'),
        ),
        migrations.AddField(
            model_name='partie',
            name='numero',
            field=models.CharField(blank=True, help_text="Numéro auto-généré: '1', '2', etc.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='souspartie',
            name='devis',
            field=models.ForeignKey(blank=True, help_text='Lien vers devis pour système unifié (null = catalogue)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties_unifiees', to='api.devis'),
        ),
        migrations.AddField(
            model_name='souspartie',
            name='index_global',
            field=models.IntegerField(blank=True, default=0, help_text='Position dans le devis (0 = catalogue, >0 = système unifié)'),
        ),
        migrations.AddField(
            model_name='souspartie',
            name='numero',
            field=models.CharField(blank=True, help_text="Numéro auto-généré: '1.1', '1.2', etc.", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LigneSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('index_global', models.IntegerField(blank=True, default=0, help_text='Position dans le devis (tous types confondus)')),
                ('numero', models.CharField(blank=True, help_text='Numéro auto-généré en fonction du contexte', max_length=50, null=True)),
                ('type_speciale', models.CharField(choices=[('reduction', 'Réduction'), ('addition', 'Addition'), ('display', 'Affichage')], default='display', max_length=50, verbose_name='Type de ligne spéciale')),
                ('value_type', models.CharField(choices=[('fixed', 'Montant fixe'), ('percentage', 'Pourcentage')], default='fixed', max_length=50, verbose_name='Type de valeur')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur')),
                ('base_calculation', models.JSONField(blank=True, help_text='Base de calcul pour les pourcentages (montant, scope, etc.)', null=True)),
                ('styles', models.JSONField(blank=True, default=dict, help_text='Styles CSS (color, backgroundColor, fontWeight, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_speciales_v3', to='api.devis')),
            ],
            options={
                'verbose_name': 'Ligne spéciale',
                'verbose_name_plural': 'Lignes spéciales',
                'ordering': ['index_global'],
            },
        ),
    ]
