# Generated by Django 5.1.1 on 2025-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_lignedetail_devis_lignedetail_index_global_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devisligne',
            options={'ordering': ['index_global']},
        ),
        migrations.AddField(
            model_name='devisligne',
            name='index_global',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Position dans le devis (1.101, 1.102, 2.201, etc.)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partie',
            name='numero',
            field=models.IntegerField(blank=True, default=0, help_text='Numéro de la partie: 1, 2, 3, etc. (0 = pas de numéro)', null=True),
        ),
    ]
