# Generated by Django 5.1.1 on 2025-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_devisligne_options_devisligne_index_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
        migrations.AlterField(
            model_name='appeloffres',
            name='state_chantier',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé'), ('En attente', 'En attente')], default='En Cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='state_chantier',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé'), ('En attente', 'En attente')], default='En Cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé'), ('En attente', 'En attente')], default='En Cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='state_quitus',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé'), ('En attente', 'En attente')], default='En Cours', max_length=20),
        ),
    ]
