# Generated by Django 5.1.1 on 2025-12-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_situation_tva_rate_alter_appeloffres_state_chantier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='chantier_transformé',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_offres_source', to='api.chantier', verbose_name="Chantier transformé depuis cet appel d'offres"),
        ),
    ]
