# Generated by Django 5.1.1 on 2025-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_appeloffres_chantier_transformé'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfournisseurmateriel',
            name='montant_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
