# Generated by Django 5.1.1 on 2025-12-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_paiementfournisseurmateriel_montant_a_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureFournisseurMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.paiementfournisseurmateriel')),
            ],
            options={
                'verbose_name': 'Facture Fournisseur Matériel',
                'verbose_name_plural': 'Factures Fournisseurs Matériel',
                'unique_together': {('paiement', 'numero_facture')},
            },
        ),
    ]
