# Generated by Django 5.1.1 on 2025-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_facturefournisseurmateriel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturefournisseurmateriel',
            name='montant_facture',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
