# Generated by Django 5.1.1 on 2025-12-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_facturefournisseurmateriel_montant_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfournisseurmateriel',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiementfournisseurmateriel',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoriqueModificationPaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('montant_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to='api.paiementfournisseurmateriel')),
            ],
            options={
                'verbose_name': 'Historique Modification Paiement Fournisseur',
                'verbose_name_plural': 'Historiques Modifications Paiements Fournisseurs',
                'ordering': ['-date_modification'],
            },
        ),
    ]
