# Generated by Django 5.1.1 on 2025-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_paiementfournisseurmateriel_date_modification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquemodificationpaiementfournisseur',
            name='montant_apres',
        ),
        migrations.RemoveField(
            model_name='historiquemodificationpaiementfournisseur',
            name='montant_avant',
        ),
        migrations.AddField(
            model_name='historiquemodificationpaiementfournisseur',
            name='date_paiement_apres',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiquemodificationpaiementfournisseur',
            name='date_paiement_avant',
            field=models.DateField(blank=True, null=True),
        ),
    ]
