# Generated by Django 5.1.1 on 2025-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_historiquemodificationpaiementfournisseur_montant_apres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfournisseurmateriel',
            name='date_envoi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementfournisseurmateriel',
            name='date_paiement_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
