# Generated by Django 5.1.1 on 2025-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_paiementfournisseurmateriel_date_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturefournisseurmateriel',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Facture payée'),
        ),
        migrations.AddField(
            model_name='facturefournisseurmateriel',
            name='date_paiement_facture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement de la facture'),
        ),
    ]

