# Generated by Django 5.1.1 on 2025-12-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_facturefournisseurmateriel_payee_and_date_paiement_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('poste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sous_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.soustraitant')),
            ],
            options={
                'verbose_name': 'Contact Sous-Traitant',
                'verbose_name_plural': 'Contacts Sous-Traitants',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
