# Generated by Django 5.1.1 on 2025-12-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_contactsoustraitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='contact_sous_traitant_contact',
            field=models.ForeignKey(blank=True, help_text='Contact spécifique du sous-traitant (si différent du représentant)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_contact', to='api.contactsoustraitant'),
        ),
    ]
