# Generated by Django 5.1.1 on 2025-12-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_boncommande_contact_sous_traitant_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, choices=[('', ''), ('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='', max_length=10, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.societe')),
            ],
            options={
                'verbose_name': 'Contact Société',
                'verbose_name_plural': 'Contacts Sociétés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='devis',
            name='contact_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='api.contactsociete', verbose_name='Contact société'),
        ),
        migrations.AddField(
            model_name='facture',
            name='contact_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='api.contactsociete', verbose_name='Contact société'),
        ),
        migrations.AddField(
            model_name='situation',
            name='contact_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to='api.contactsociete', verbose_name='Contact société'),
        ),
    ]
