# Generated by Django 5.1.1 on 2025-12-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_contactsociete_devis_contact_societe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauSousTraitantEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_traitant', models.CharField(max_length=255)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('date_paiement_prevue', models.DateField(blank=True, null=True)),
                ('delai_paiement', models.IntegerField(default=45)),
                ('source_type', models.CharField(choices=[('facture', 'Facture Sous-Traitant'), ('agent_journalier', 'Agent Journalier'), ('agency_expense', 'Dépense Agence'), ('manual', 'Saisie Manuelle')], default='manual', max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableau_sous_traitant_entries', to='api.chantier')),
            ],
            options={
                'verbose_name': 'Entrée Tableau Sous-Traitant',
                'verbose_name_plural': 'Entrées Tableau Sous-Traitant',
                'ordering': ['chantier', 'sous_traitant', 'annee', 'mois'],
                'unique_together': {('chantier', 'sous_traitant', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='FactureTableauSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=255)),
                ('montant_facture', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payee', models.BooleanField(default=False, verbose_name='Facture payée')),
                ('date_paiement_facture', models.DateField(blank=True, null=True, verbose_name='Date de paiement de la facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.tableausoustraitantentry')),
            ],
            options={
                'verbose_name': 'Facture Tableau Sous-Traitant',
                'verbose_name_plural': 'Factures Tableau Sous-Traitant',
                'unique_together': {('entry', 'numero_facture')},
            },
        ),
    ]
