# Generated by Django 5.1.1 on 2025-12-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_agencyexpense_add_sous_traitant_and_chantier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableausoustraitantentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tableausoustraitantentry',
            name='chantier',
        ),
        migrations.DeleteModel(
            name='FactureTableauSousTraitant',
        ),
        migrations.DeleteModel(
            name='TableauSousTraitantEntry',
        ),
    ]
