# Generated by Django 5.1.1 on 2025-12-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_tableausoustraitantentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyExpenseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('is_ecole_expense', models.BooleanField(default=False)),
                ('ecole_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_expenses_month', to='api.chantier')),
                ('source_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_entries', to='api.agencyexpense')),
                ('sous_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_expenses_month', to='api.soustraitant')),
            ],
            options={
                'verbose_name': 'Dépense Mensuelle Agence',
                'verbose_name_plural': 'Dépenses Mensuelles Agence',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='api_agencye_year_598ba1_idx'), models.Index(fields=['category', 'year', 'month'], name='api_agencye_categor_4ebce1_idx')],
                'unique_together': {('description', 'category', 'month', 'year')},
            },
        ),
    ]
