# Generated by Django 5.1.1 on 2025-12-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_agencyexpensemonth_factures'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviPaiementSousTraitantMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('sous_traitant', models.CharField(max_length=255)),
                ('montant_paye_ht', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('date_paiement_reel', models.DateField(blank=True, null=True)),
                ('date_envoi_facture', models.DateField(blank=True, null=True)),
                ('date_paiement_prevue', models.DateField(blank=True, null=True)),
                ('delai_paiement', models.IntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis_paiements_sous_traitant', to='api.chantier')),
            ],
            options={
                'verbose_name': 'Suivi Paiement Sous-Traitant Mensuel',
                'verbose_name_plural': 'Suivis Paiements Sous-Traitants Mensuels',
                'ordering': ['annee', 'mois', 'sous_traitant', 'chantier'],
            },
        ),
        migrations.CreateModel(
            name='FactureSuiviSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=255)),
                ('montant_facture_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payee', models.BooleanField(default=False)),
                ('date_paiement_facture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suivi_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_suivi', to='api.suivipaiementsoustraitantmensuel')),
            ],
            options={
                'verbose_name': 'Facture Suivi Sous-Traitant',
                'verbose_name_plural': 'Factures Suivi Sous-Traitants',
                'ordering': ['suivi_paiement', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suivipaiementsoustraitantmensuel',
            index=models.Index(fields=['mois', 'annee', 'sous_traitant'], name='api_suivipa_mois_259152_idx'),
        ),
        migrations.AddIndex(
            model_name='suivipaiementsoustraitantmensuel',
            index=models.Index(fields=['chantier', 'mois', 'annee'], name='api_suivipa_chantie_12c39c_idx'),
        ),
    ]
