# Generated by Django 5.1.1 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_add_suivi_paiement_sous_traitant_mensuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='date_paiement_reel',
            field=models.DateField(blank=True, help_text='Date de paiement effectif', null=True),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='date_reception_facture',
            field=models.DateField(blank=True, help_text='Date de réception de la facture (clarification)', null=True),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='delai_paiement',
            field=models.IntegerField(default=45, help_text='Délai de paiement en jours'),
        ),
        migrations.AlterField(
            model_name='agencyexpensemonth',
            name='date_paiement',
            field=models.DateField(blank=True, help_text='Date de réception de la facture (mal nommé pour compatibilité)', null=True),
        ),
    ]
