# Generated by Django 5.1.1 on 2025-12-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_date_fields_to_agency_expense_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='closed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='is_recurring_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_children', to='api.agencyexpensemonth'),
        ),
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='recurrence_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
