# Generated by Django 5.1.1 on 2026-01-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_agencyexpensemonth_closed_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='AjustementAgentJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant_ajustement', models.DecimalField(decimal_places=2, default=0, help_text="Montant de l'ajustement (positif ou négatif)", max_digits=12)),
                ('description', models.CharField(blank=True, help_text="Description de l'ajustement (ex: Gasoil, Prime, Déduction)", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_journalier', to='api.agent')),
            ],
            options={
                'verbose_name': 'Ajustement Agent Journalier',
                'verbose_name_plural': 'Ajustements Agents Journaliers',
                'ordering': ['annee', 'mois', 'agent'],
                'indexes': [models.Index(fields=['agent', 'mois', 'annee'], name='api_ajustem_agent_i_7c2a00_idx')],
                'unique_together': {('agent', 'mois', 'annee')},
            },
        ),
    ]
