# Generated by Django 5.1.1 on 2026-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_schedule_year_ajustementagentjournalier'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='assistance_maitrise_ouvrage_contact',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Contact assistance maîtrise d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='assistance_maitrise_ouvrage_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email assistance maîtrise d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='assistance_maitrise_ouvrage_nom_societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom société assistance maîtrise d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='assistance_maitrise_ouvrage_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone assistance maîtrise d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_oeuvre_contact',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Contact maître d'oeuvre"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_oeuvre_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email maître d'oeuvre"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_oeuvre_nom_societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom société maître d'oeuvre"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_oeuvre_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone maître d'oeuvre"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_ouvrage_contact',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Contact maître d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_ouvrage_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email maître d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_ouvrage_nom_societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom société maître d'ouvrage"),
        ),
        migrations.AddField(
            model_name='chantier',
            name='maitre_ouvrage_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone maître d'ouvrage"),
        ),
    ]
