# Generated by Django 5.1.1 on 2026-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_chantier_assistance_maitrise_ouvrage_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='drive_path',
            field=models.CharField(blank=True, help_text='Chemin personnalisé dans le drive. Si vide, sera calculé automatiquement à partir du nom de la société et du chantier.', max_length=500, null=True, verbose_name='Chemin du drive'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='drive_path',
            field=models.CharField(blank=True, help_text='Chemin personnalisé dans le drive. Si vide, sera calculé automatiquement à partir du nom de la société et du chantier.', max_length=500, null=True, verbose_name='Chemin du drive'),
        ),
    ]
