# Generated by Django 5.1.1 on 2026-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_clean_drive_path_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratsoustraitance',
            name='sans_contrat',
            field=models.BooleanField(default=False, help_text='Si True, ce contrat est juste une association sans document formel', verbose_name='Association sans contrat'),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='adresse_prestation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création du contrat'),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='description_prestation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='duree',
            field=models.CharField(blank=True, default="Jusqu'à livraison du chantier", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='montant_operation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='nom_maitre_oeuvre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom du maître d'œuvre"),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='nom_maitre_ouvrage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom du maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='nom_operation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
