# Generated by Django 5.1.1 on 2026-01-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_contratsoustraitance_sans_contrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='type_contrat',
            field=models.CharField(choices=[('BTP', 'BTP'), ('NETTOYAGE', 'Nettoyage'), ('SANS_CONTRAT', 'Sans contrat documenté')], default='NETTOYAGE', max_length=20),
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='api.fournisseur')),
            ],
            options={
                'unique_together': {('fournisseur', 'nom')},
            },
        ),
    ]
