# Generated by Django 5.1.1 on 2026-01-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_contratsoustraitance_type_contrat_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='magasin',
            field=models.ForeignKey(blank=True, help_text='Magasin du fournisseur pour le retrait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande', to='api.magasin'),
        ),
    ]
