# Generated by Django 5.1.1 on 2026-01-23 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_boncommande_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
