# Generated by Django 5.1.1 on 2026-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_distributeur_distributeurmouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeur',
            name='grid_columns',
            field=models.JSONField(blank=True, default=list, help_text='Nombre de colonnes par ligne [col1, col2, ...]'),
        ),
        migrations.AddField(
            model_name='distributeur',
            name='grid_rows',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de lignes dans la grille'),
        ),
    ]
