# Generated by Django 5.1.1 on 2026-01-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_distributeur_grid_columns_distributeur_grid_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeurCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Index de la ligne (0-based)')),
                ('col_index', models.PositiveIntegerField(help_text='Index de la colonne (0-based)')),
                ('nom_produit', models.CharField(blank=True, help_text='Nom du produit (ex: Chips Lays)', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image (S3 ou externe)", max_length=500, null=True)),
                ('image_s3_key', models.CharField(blank=True, help_text='Clé S3 si image uploadée', max_length=500, null=True)),
                ('image_position', models.CharField(choices=[('center', 'Centré'), ('top', 'Haut'), ('bottom', 'Bas'), ('left', 'Gauche'), ('right', 'Droite')], default='center', help_text="Position de l'image dans la case", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.distributeur')),
            ],
            options={
                'ordering': ['row_index', 'col_index'],
                'unique_together': {('distributeur', 'row_index', 'col_index')},
            },
        ),
    ]
