# Generated by Django 5.1.1 on 2026-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_distributeurcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit', max_length=150)),
                ('nom_produit', models.CharField(blank=True, help_text='Nom alternatif du produit', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image (externe)", max_length=500, null=True)),
                ('image_s3_key', models.CharField(blank=True, help_text='Clé S3 si image uploadée', max_length=500, null=True)),
                ('image_position', models.CharField(choices=[('center', 'Centré'), ('top', 'Haut'), ('bottom', 'Bas'), ('left', 'Gauche'), ('right', 'Droite')], default='center', help_text="Position de l'image", max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0, help_text='Quantité en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit Stock Mobile',
                'verbose_name_plural': 'Produits Stock Mobile',
                'ordering': ['nom'],
            },
        ),
    ]
