# Generated by Django 5.1.1 on 2026-01-28 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_stockproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_achat', models.CharField(help_text="Lieu d'achat (ex: Leclerc, Intermarché)", max_length=150)),
                ('date_achat', models.DateTimeField(default=django.utils.timezone.now, help_text="Date de l'achat")),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text="Total de l'achat", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achat de Stock',
                'verbose_name_plural': 'Achats de Stock',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='StockPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(help_text='Nom du produit (si nouveau)', max_length=150)),
                ('quantite', models.PositiveIntegerField(help_text='Quantité achetée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix à l'unité", max_digits=10)),
                ('unite', models.CharField(help_text='Unité (ex: pièce, kg, L)', max_length=50)),
                ('creer_produit', models.BooleanField(default=False, help_text="Créer le produit dans le stock après l'achat")),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.stockpurchase')),
                ('produit', models.ForeignKey(blank=True, help_text='Produit existant (si null, produit nouveau)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='api.stockproduct')),
            ],
            options={
                'verbose_name': 'Produit Acheté',
                'verbose_name_plural': 'Produits Achetés',
            },
        ),
    ]
