# Generated by Django 5.1.1 on 2026-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_add_fields_to_stockpurchaseitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockpurchaseitem',
            name='api_stockpr_achat_id_idx',
        ),
        migrations.RenameIndex(
            model_name='stockpurchaseitem',
            new_name='api_stockpu_produit_fdff81_idx',
            old_name='api_stockpr_produit_idx',
        ),
        migrations.AlterField(
            model_name='stockpurchaseitem',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, help_text='Total pour cet item (quantité × prix_unitaire)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpurchaseitem',
            name='nom_produit',
            field=models.CharField(help_text='Nom du produit', max_length=150),
        ),
        migrations.AlterField(
            model_name='stockpurchaseitem',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat à l'unité", max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpurchaseitem',
            name='quantite',
            field=models.PositiveIntegerField(help_text='Nombre de pièces achetées'),
        ),
        migrations.AddIndex(
            model_name='stockpurchaseitem',
            index=models.Index(fields=['achat', '-created_at'], name='api_stockpu_achat_i_db5be3_idx'),
        ),
    ]
