# Generated by Django 5.1.1 on 2026-01-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_remove_stockpurchaseitem_api_stockpr_achat_id_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_restante', models.PositiveIntegerField(help_text='Quantité encore disponible dans ce lot')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat à l'unité (copie)", max_digits=10)),
                ('date_achat', models.DateTimeField(help_text="Date d'achat (copie)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(help_text='Produit concerné', on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.stockproduct')),
                ('purchase_item', models.ForeignKey(help_text="Item d'achat d'origine", on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.stockpurchaseitem')),
            ],
            options={
                'verbose_name': 'Lot de Stock',
                'verbose_name_plural': 'Lots de Stock',
                'ordering': ['date_achat', 'created_at'],
                'indexes': [models.Index(fields=['produit', 'date_achat'], name='api_stocklo_produit_70fb46_idx'), models.Index(fields=['produit', 'quantite_restante'], name='api_stocklo_produit_7c4f8e_idx')],
            },
        ),
    ]
