# Generated by Django 5.1.1

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_add_stocklot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'unités perdues")),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text='Coût total des pertes (calculé en FIFO à partir des lots)', max_digits=10)),
                ('date_perte', models.DateTimeField(default=timezone.now, help_text='Date de la perte')),
                ('commentaire', models.CharField(blank=True, help_text='Ex: casse, vol, péremption...', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(help_text='Produit concerné', on_delete=django.db.models.deletion.CASCADE, related_name='pertes', to='api.stockproduct')),
            ],
            options={
                'verbose_name': 'Perte de Stock',
                'verbose_name_plural': 'Pertes de Stock',
                'ordering': ['-date_perte'],
                'indexes': [
                    models.Index(fields=['produit', '-date_perte'], name='api_stocklo_produit_8a2b1c_idx'),
                ],
            },
        ),
    ]
