# Generated by Django 5.1.1 on 2026-01-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_stockloss'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockloss',
            new_name='api_stocklo_produit_60cc36_idx',
            old_name='api_stocklo_produit_8a2b1c_idx',
        ),
    ]
