# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_api_stocklo_produit_8a2b1c_idx_api_stocklo_produit_60cc36_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeurcell',
            name='prix_vente',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Prix de vente (€) pour le calcul du bénéfice par produit',
                max_digits=10,
                null=True
            ),
        ),
    ]
