# Generated by Django 5.1.1

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_distributeurcell_prix_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeurVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text="Nombre d'unités vendues")),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente à l\'instant T (€) — stocké pour calculs exacts', max_digits=10)),
                ('date_vente', models.DateTimeField(default=timezone.now, help_text='Date et heure de la vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(help_text='Case (produit) vendu', on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='api.distributeurcell')),
                ('distributeur', models.ForeignKey(help_text='Distributeur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='api.distributeur')),
            ],
            options={
                'verbose_name': 'Vente distributeur',
                'verbose_name_plural': 'Ventes distributeur',
                'ordering': ['-date_vente'],
                'indexes': [
                    models.Index(fields=['distributeur', '-date_vente'], name='api_distrib_distri_8b2c1d_idx'),
                    models.Index(fields=['cell', '-date_vente'], name='api_distrib_cell_i_9c3d2e_idx'),
                ],
            },
        ),
    ]
