# Generated by Django 5.1.1

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_distributeurvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeurReapproSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=timezone.now, help_text='Début du mouvement')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin du mouvement (quand terminé)', null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', help_text='En cours ou Terminé', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributeur', models.ForeignKey(help_text='Distributeur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='reappro_sessions', to='api.distributeur')),
            ],
            options={
                'verbose_name': 'Session réappro distributeur',
                'verbose_name_plural': 'Sessions réappro distributeur',
                'ordering': ['-date_debut'],
                'indexes': [
                    models.Index(fields=['distributeur', '-date_debut'], name='api_distrib_distri_9c3d1e_idx'),
                    models.Index(fields=['statut'], name='api_distrib_statut_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DistributeurReapproLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text="Nombre d'unités ajoutées")),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente (€) au moment du mouvement — pour calcul bénéfice', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(help_text='Case réapprovisionnée', on_delete=django.db.models.deletion.CASCADE, related_name='reappro_lignes', to='api.distributeurcell')),
                ('session', models.ForeignKey(help_text='Session de réappro', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.distributeurreapprosession')),
            ],
            options={
                'verbose_name': 'Ligne réappro',
                'verbose_name_plural': 'Lignes réappro',
                'ordering': ['session', 'cell'],
                'unique_together': {('session', 'cell')},
                'indexes': [
                    models.Index(fields=['session'], name='api_distrib_session_idx'),
                ],
            },
        ),
    ]
