# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_distributeurreappro'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeurreapproligne',
            name='cout_unitaire',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text='Coût unitaire (€) issu des StockLot — pour calcul bénéfice',
                max_digits=10,
                null=True
            ),
        ),
    ]
