# Generated by Django (link DistributeurCell -> StockProduct)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_distributeurreapproligne_cout_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeurcell',
            name='stock_product',
            field=models.ForeignKey(
                blank=True,
                help_text='Produit du stock lié à cette case (même liste) — pour coût et bénéfice',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='distributeur_cells',
                to='api.stockproduct',
            ),
        ),
    ]
