# Generated by Django 5.1.1 on 2026-01-29 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_distributeurcell_stock_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeurFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ex: Frais banque TPE, Entretien machine', max_length=255)),
                ('date_frais', models.DateField(default=django.utils.timezone.now, help_text='Date du frais')),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Montant en € (positif = coût)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frais distributeur',
                'verbose_name_plural': 'Frais distributeur',
                'ordering': ['-date_frais', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='distributeurreapproligne',
            new_name='api_distrib_session_54e03c_idx',
            old_name='api_distrib_session_idx',
        ),
        migrations.RenameIndex(
            model_name='distributeurreapprosession',
            new_name='api_distrib_distrib_f695e3_idx',
            old_name='api_distrib_distri_9c3d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='distributeurreapprosession',
            new_name='api_distrib_statut_3d0d1a_idx',
            old_name='api_distrib_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='distributeurvente',
            new_name='api_distrib_distrib_2fbf13_idx',
            old_name='api_distrib_distri_8b2c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='distributeurvente',
            new_name='api_distrib_cell_id_29ff33_idx',
            old_name='api_distrib_cell_i_9c3d2e_idx',
        ),
        migrations.AlterField(
            model_name='distributeurreapproligne',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente (€) au moment du mouvement', max_digits=10),
        ),
        migrations.AddField(
            model_name='distributeurfrais',
            name='distributeur',
            field=models.ForeignKey(help_text='Distributeur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='api.distributeur'),
        ),
    ]
