# Generated by Django 5.1.1 on 2026-01-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_distributeur_frais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeurfrais',
            name='date_frais',
            field=models.DateField(help_text='Date du frais'),
        ),
        migrations.AlterField(
            model_name='distributeurfrais',
            name='description',
            field=models.CharField(help_text='Ex: Frais banque TPE, Entretien mensuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='distributeurfrais',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant en € (toujours positif, déduit du bénéfice)', max_digits=10),
        ),
    ]
