# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_distributeurfrais'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeurfrais',
            name='category',
            field=models.CharField(
                choices=[('bancaire', 'Frais bancaire / TPE'), ('maintenance', 'Maintenance / Entretien'), ('autre', 'Autre')],
                default='autre',
                help_text='Type de frais pour regroupement (bancaire, maintenance, etc.)',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='distributeurfrais',
            name='recurrence',
            field=models.CharField(
                blank=True,
                choices=[('', 'Ponctuel'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')],
                default='',
                help_text='Si récurrent : mensuel, hebdomadaire (pour regroupement par période)',
                max_length=20,
            ),
        ),
    ]
