# Generated by Django 5.1.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_distributeurfrais_category_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapFinancierPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseurs_visibles', models.JSONField(blank=True, default=None, null=True)),
                ('chantier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recap_financier_preference', to='api.chantier')),
            ],
            options={
                'verbose_name': 'Préférence Récap Financier',
                'verbose_name_plural': 'Préférences Récap Financier',
            },
        ),
    ]
