# Generated by Django 5.1.1 on 2026-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_distributeurfrais_category_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, default='', max_length=50, verbose_name='Forme juridique')),
                ('capital', models.CharField(blank=True, default='', max_length=50, verbose_name='Capital social')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('rcs', models.CharField(blank=True, default='', max_length=100, verbose_name='RCS')),
                ('siret', models.CharField(blank=True, default='', max_length=50, verbose_name='SIRET')),
                ('tva_intra', models.CharField(blank=True, default='', max_length=50, verbose_name='TVA intracommunautaire')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('representant_nom', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du représentant')),
                ('representant_fonction', models.CharField(blank=True, default='', max_length=100, verbose_name='Fonction du représentant')),
                ('nom_application', models.CharField(default='Webapplication P3000', max_length=100, verbose_name="Nom de l'application")),
                ('domaine_public', models.CharField(blank=True, default='', help_text='Ex: myp3000app.com', max_length=200, verbose_name='Domaine public')),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configuration entreprise',
            },
        ),
    ]
