# Generated by Django 5.1.1 on 2026-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_recap_financier_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenant',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
