# Generated by Django 5.1.1 on 2026-03-12 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_add_entreprise_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=500, verbose_name='Localisation')),
                ('probleme', models.TextField(verbose_name='Problème constaté')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('prestation_possible', models.BooleanField(default=True, verbose_name='Prestation possible')),
                ('prestation_realisee', models.TextField(blank=True, default='', verbose_name='Prestations réalisées')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prestation de rapport',
                'verbose_name_plural': 'Prestations de rapport',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TitreRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Titre de rapport',
                'verbose_name_plural': 'Titres de rapport',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='societe',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clé S3 du logo'),
        ),
        migrations.CreateModel(
            name='PhotoRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('type_photo', models.CharField(choices=[('avant', 'Avant travaux'), ('en_cours', 'En cours de travaux'), ('apres', 'Après travaux')], default='avant', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.prestationrapport')),
            ],
            options={
                'verbose_name': 'Photo de rapport',
                'verbose_name_plural': 'Photos de rapport',
                'ordering': ['type_photo', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('objet_recherche', models.TextField(verbose_name='Objet de la recherche')),
                ('resultat', models.TextField(blank=True, default='', verbose_name='Résultat')),
                ('adresse_residence', models.CharField(max_length=500, verbose_name='Adresse résidence')),
                ('locataire_nom', models.CharField(blank=True, default='', max_length=100)),
                ('locataire_prenom', models.CharField(blank=True, default='', max_length=100)),
                ('locataire_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('locataire_email', models.EmailField(blank=True, default='', max_length=254)),
                ('signature_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('type_rapport', models.CharField(choices=[('intervention', "Rapport d'intervention"), ('vigik_plus', 'Vigik+')], default='intervention', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('pdf_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention', to='api.chantier')),
                ('client_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention', to='api.societe', verbose_name='Client / Bailleur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_intervention', to='api.agent')),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports', to='api.titrerapport')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prestationrapport',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='api.rapportintervention'),
        ),
    ]
