# Generated by Django 5.1.1 on 2026-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_prestationrapport_titrerapport_societe_logo_s3_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintervention',
            name='technicien',
            field=models.CharField(max_length=255, verbose_name='Technicien'),
        ),
    ]
