# Generated by Django 5.1.1 on 2026-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_avenant_numero_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
