# Generated by Django 5.1.1 on 2026-03-12 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_rapportintervention_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorapport',
            name='date_photo',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de la photo'),
        ),
    ]
