# Generated by Django 5.1.1 on 2026-02-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_stock_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='societe_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_affichage', to='api.societe', verbose_name='Société pour affichage devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='societe_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_affichage', to='api.societe', verbose_name='Société pour affichage facture'),
        ),
        migrations.AddField(
            model_name='situation',
            name='societe_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations_affichage', to='api.societe', verbose_name='Société pour affichage situation'),
        ),
    ]
