# Generated by Django 5.1.1 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_photorapport_date_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='logements_visites',
            field=models.TextField(blank=True, default='', verbose_name='Logements visités'),
        ),
    ]
