# Generated by Django 5.1.1 on 2026-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_devis_societe_devis_facture_societe_devis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
