# Generated by Django 5.1.1 on 2026-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_rapportintervention_logements_visites'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='nom_residence',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de la résidence'),
        ),
    ]
