# Generated by Django 5.1.1 on 2026-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_agencyexpensemonth_montant_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyexpensemonth',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Montant payé (suivi tableau fournisseur, dépenses agence)', max_digits=10, null=True),
        ),
    ]
