# Generated by Django 5.1.1 on 2026-03-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_rapportintervention_nom_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportintervention',
            name='adresse_residence',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='logements_visites',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='nom_residence',
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='logement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Logement'),
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la résidence')),
                ('adresse', models.CharField(blank=True, default='', max_length=500, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences', to='api.chantier')),
                ('client_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences', to='api.societe', verbose_name='Client / Bailleur')),
            ],
            options={
                'verbose_name': 'Résidence',
                'verbose_name_plural': 'Résidences',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='api.residence', verbose_name='Résidence'),
        ),
    ]
