# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_rapportintervention_statut_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepriseconfig',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clé S3 du logo (login mobile)'),
        ),
    ]
