# Generated by Django 5.1.1 on 2026-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_populate_default_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyexpensemonth',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
