# Generated by Django 5.1.1 on 2026-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_entrepriseconfig_logo_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='numero_batiment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro du bâtiment'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='photo_platine_s3_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Photo platine'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='presence_platine_portail',
            field=models.BooleanField(blank=True, null=True, verbose_name='Présence de platine au niveau du portail'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='type_installation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Type d'installation"),
        ),
    ]
