# Generated by Django 5.1.1 on 2026-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_vigik_plus_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='photo_platine_portail_s3_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Photo platine portail'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='presence_platine',
            field=models.BooleanField(blank=True, null=True, verbose_name='Présence de platine'),
        ),
    ]
