# Generated by Django 5.1.1 on 2026-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_vigik_plus_deux_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='adresse_vigik',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Adresse (rapport Vigik+)'),
        ),
    ]
