# Generated by Django 5.1.1 on 2026-04-08 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_stockproductbestpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['id'], 'verbose_name': 'Agence', 'verbose_name_plural': 'Agences'},
        ),
        migrations.AddField(
            model_name='agentprime',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primes_agence', to='api.agence'),
        ),
        migrations.AddIndex(
            model_name='agentprime',
            index=models.Index(fields=['agence', 'mois', 'annee'], name='api_agentpr_agence__52ce17_idx'),
        ),
    ]
