# Generated by Django 5.1.1 on 2026-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_add_agence_to_agentprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
