# Generated by Django 5.1.1 on 2026-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_add_comment_to_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedetail',
            name='taux_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
