# Generated by Django 5.1.1 on 2026-03-24 17:14

import api.models_rapport
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_rapportintervention_dates_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintervention',
            name='dates_intervention',
            field=models.JSONField(blank=True, default=api.models_rapport.default_dates_intervention_list, help_text='Liste ordonnée de dates ISO (YYYY-MM-DD) : 1er passage, 2e, etc.', verbose_name="Dates d'intervention (passages)"),
        ),
    ]
