# Generated by Django 5.1.1 on 2026-04-17 15:35

import api.models_rapport
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_client_name_surname_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=500, verbose_name='Localisation')),
                ('probleme', models.TextField(verbose_name='Problème constaté')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('prestation_possible', models.BooleanField(default=True, verbose_name='Prestation possible')),
                ('prestation_realisee', models.TextField(blank=True, default='', verbose_name='Prestations réalisées')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prestation de rapport',
                'verbose_name_plural': 'Prestations de rapport',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RapportInterventionNumeroCompteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur numéro rapport (par année)',
                'verbose_name_plural': 'Compteurs numéros rapport (par année)',
            },
        ),
        migrations.CreateModel(
            name='TitreRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Titre de rapport',
                'verbose_name_plural': 'Titres de rapport',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='societe',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clé S3 du logo'),
        ),
        migrations.CreateModel(
            name='PhotoRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('type_photo', models.CharField(choices=[('avant', 'Avant travaux'), ('en_cours', 'En cours de travaux'), ('apres', 'Après travaux')], default='avant', max_length=20)),
                ('date_photo', models.DateField(default=datetime.date.today, verbose_name='Date de la photo')),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.prestationrapport')),
            ],
            options={
                'verbose_name': 'Photo de rapport',
                'verbose_name_plural': 'Photos de rapport',
                'ordering': ['type_photo', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dates_intervention', models.JSONField(blank=True, default=api.models_rapport.default_dates_intervention_list, help_text='Liste ordonnée de dates ISO (YYYY-MM-DD) : 1er passage, 2e, etc.', verbose_name="Dates d'intervention (passages)")),
                ('technicien', models.CharField(max_length=255, verbose_name='Technicien')),
                ('objet_recherche', models.TextField(verbose_name='Objet de la recherche')),
                ('resultat', models.TextField(blank=True, default='', verbose_name='Résultat')),
                ('temps_trajet', models.FloatField(default=0, verbose_name='Temps de trajet (heures)')),
                ('temps_taches', models.FloatField(default=0, verbose_name='Temps de taches (heures)')),
                ('logement', models.CharField(blank=True, default='', max_length=255, verbose_name='Logement')),
                ('locataire_nom', models.CharField(blank=True, default='', max_length=100)),
                ('locataire_prenom', models.CharField(blank=True, default='', max_length=100)),
                ('locataire_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('locataire_email', models.EmailField(blank=True, default='', max_length=254)),
                ('signature_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('type_rapport', models.CharField(choices=[('intervention', "Rapport d'intervention"), ('vigik_plus', 'Vigik+')], default='intervention', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('a_faire', 'A faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20)),
                ('devis_a_faire', models.BooleanField(default=False, verbose_name='Devis à faire')),
                ('devis_fait', models.BooleanField(default=False, verbose_name='Devis fait')),
                ('pdf_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('numero_rapport', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de rapport (séquentiel annuel)')),
                ('annee_numero_rapport', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année du numéro de rapport')),
                ('adresse_vigik', models.CharField(blank=True, default='', max_length=500, verbose_name='Adresse (rapport Vigik+)')),
                ('numero_batiment', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro du bâtiment')),
                ('type_installation', models.CharField(blank=True, default='', max_length=255, verbose_name="Type d'installation")),
                ('presence_platine', models.BooleanField(blank=True, null=True, verbose_name='Présence de platine')),
                ('photos_platine_s3_keys', models.JSONField(blank=True, default=list, help_text='Liste ordonnée de clés S3.', verbose_name='Photos platine (Vigik+)')),
                ('presence_portail', models.BooleanField(blank=True, null=True, verbose_name="Présence d'un portail (Vigik+)")),
                ('presence_platine_portail', models.BooleanField(blank=True, null=True, verbose_name='Présence de platine au niveau du portail')),
                ('photos_platine_portail_s3_keys', models.JSONField(blank=True, default=list, help_text='Liste ordonnée de clés S3.', verbose_name='Photos platine portail (Vigik+)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention', to='api.chantier')),
                ('client_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention', to='api.societe', verbose_name='Client / Bailleur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('devis_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention_lies', to='api.devis', verbose_name='Devis lié')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prestationrapport',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='api.rapportintervention'),
        ),
        migrations.CreateModel(
            name='RapportInterventionBrouillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('champs_manquants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_intervention_brouillons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Brouillon de rapport d'intervention",
                'verbose_name_plural': "Brouillons de rapports d'intervention",
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la résidence')),
                ('adresse', models.CharField(blank=True, default='', max_length=500, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences', to='api.chantier')),
                ('client_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences', to='api.societe', verbose_name='Client / Bailleur')),
            ],
            options={
                'verbose_name': 'Résidence',
                'verbose_name_plural': 'Résidences',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='api.residence', verbose_name='Résidence'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='titre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='api.titrerapport'),
        ),
    ]
