# Generated by Django 5.1.1 on 2026-04-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_agent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Premier jour du mois (YYYY-MM-01)')),
                ('salaire_net_initial_hors_prime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accompte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paiement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('salaire_overridden', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_mensuels', to='api.agent')),
            ],
            options={
                'ordering': ['month', 'agent_id'],
                'unique_together': {('agent', 'month')},
            },
        ),
    ]
