# Generated by Django 5.1.1 on 2026-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_pointagemensuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointagemensuel',
            name='montant_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pointagemensuel',
            name='montant_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
