# Generated by Django 5.1.1 on 2026-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_pointagemensuel_montant_brut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointagemensuel',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
