# Generated by Django 5.1.1 on 2026-04-07 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_rapportintervention_statut_brouillon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportInterventionBrouillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('champs_manquants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_intervention_brouillons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Brouillon de rapport d'intervention",
                'verbose_name_plural': "Brouillons de rapports d'intervention",
                'ordering': ['-updated_at'],
            },
        ),
    ]
