# Generated by Django 5.1.1 on 2026-04-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_pointage_mensuel_date_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, help_text='Clé fixe pour une seule configuration applicative.', max_length=40, unique=True)),
                ('depenses_agence_use_default', models.BooleanField(default=True, help_text='Si vrai, la carte applique la règle « première agence » (id minimal).')),
                ('depenses_agence_included_agence_ids', models.JSONField(blank=True, default=list, help_text="Ids d'agence et/ou null pour « Non rattaché » ; utilisé si use_default est faux.")),
                ('extra', models.JSONField(blank=True, default=dict, help_text="Champs futurs (filtres, options d'affichage, etc.).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres dashboard',
                'verbose_name_plural': 'Paramètres dashboard',
            },
        ),
    ]
