# Generated by Django 5.1.1 on 2026-04-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_dashboard_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMobileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_rapports', models.BooleanField(default=False, verbose_name='Accès Rapports')),
                ('can_access_distributeur', models.BooleanField(default=False, verbose_name='Accès Distributeur')),
                ('can_access_drive', models.BooleanField(default=False, verbose_name='Accès Drive')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès mobile utilisateur',
                'verbose_name_plural': 'Accès mobiles utilisateurs',
            },
        ),
    ]
