# Generated by Django 5.1.1 on 2026-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_add_user_mobile_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointagemensuel',
            name='agence',
            field=models.BooleanField(default=False),
        ),
    ]
