# Generated by Django 5.1.1 on 2026-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_rapportintervention_presence_portail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='rue_societe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='societe',
            name='ville_societe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
