# Generated by Django 5.1.1 on 2026-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_pointagemensuel_repartition_montant_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointagemensuel',
            name='repartition_montant_charge',
            field=models.JSONField(blank=True, default=list, help_text='[{"agence_id": <int ou null>, "montant": <nombre>}, ...] ; somme = montant_charge.'),
        ),
    ]
