# Generated by Django 5.1.1 on 2026-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_pointagemensuel_repartition_montant_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedetail',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
