# Generated by Django 5.1.1 on 2026-08-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_agentperiodeinactivite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('libelle_normalise', models.CharField(db_index=True, max_length=255)),
                ('type_element', models.CharField(choices=[('titre', 'Titre'), ('ligne', 'Ligne')], default='ligne', max_length=10)),
                ('couleur_defaut', models.CharField(blank=True, default='', max_length=7)),
                ('nb_utilisations', models.IntegerField(default=1)),
                ('derniere_utilisation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Désignation Gantt',
                'verbose_name_plural': 'Désignations Gantt',
                'ordering': ['-nb_utilisations', '-derniere_utilisation'],
            },
        ),
        migrations.CreateModel(
            name='GanttDiagramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du diagramme')),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('echelle', models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois')], default='semaine', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagramme de Gantt',
                'verbose_name_plural': 'Diagrammes de Gantt',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='GanttElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('titre', 'Titre'), ('ligne', 'Ligne')], default='ligne', max_length=10)),
                ('libelle', models.CharField(max_length=255, verbose_name='Désignation')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('couleur', models.CharField(default='#1976d2', max_length=7)),
                ('ordre', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Élément de diagramme',
                'verbose_name_plural': 'Éléments de diagramme',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GanttHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('validation', 'Validation'), ('reouverture', 'Réouverture'), ('modif_diagramme', 'Modification du diagramme'), ('ajout_element', 'Ajout'), ('modif_element', 'Modification'), ('suppression_element', 'Suppression')], max_length=30)),
                ('description', models.TextField(help_text="Phrase lisible affichée telle quelle à l'utilisateur")),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique de diagramme',
                'verbose_name_plural': 'Historiques de diagramme',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='lignemasqueetableaufournisseur',
            new_name='api_lignema_mois_b68241_idx',
            old_name='api_lignema_mois_a_fq_idx',
        ),
        migrations.RenameIndex(
            model_name='lignemasqueetableausoustraitant',
            new_name='api_lignema_mois_bb46e4_idx',
            old_name='api_lignema_mois_a7c1d0_idx',
        ),
        migrations.AddField(
            model_name='ganttdesignation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ganttdiagramme',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagrammes_gantt', to='api.chantier', verbose_name='Chantier lié (optionnel)'),
        ),
        migrations.AddField(
            model_name='ganttdiagramme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_diagrammes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ganttdiagramme',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_diagrammes_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ganttdiagramme',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_diagrammes_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ganttelement',
            name='diagramme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.ganttdiagramme'),
        ),
        migrations.AddField(
            model_name='ganttelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='api.ganttelement'),
        ),
        migrations.AddField(
            model_name='gantthistorique',
            name='diagramme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.ganttdiagramme'),
        ),
        migrations.AddField(
            model_name='gantthistorique',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ganttdesignation',
            unique_together={('libelle_normalise', 'type_element')},
        ),
    ]
