# Generated by Django 5.1.1 on 2026-08-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_merge_20260516_1639'),
        ('api', '0129_situation_list_indexes'),
    ]

    operations = [
    ]
