# Generated by Django 5.1.1 on 2026-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_agent_phone_number_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganttelement',
            name='style_barre',
            field=models.CharField(choices=[('plein', 'Plein'), ('leger', 'Léger'), ('degrade', 'Dégradé'), ('hachure', 'Hachuré'), ('hachure_croise', 'Hachure croisée'), ('rayures_v', 'Rayures verticales'), ('rayures_h', 'Rayures horizontales'), ('damier', 'Damier'), ('contour', 'Contour'), ('contour_epais', 'Contour épais'), ('double', 'Double contour'), ('pointille', 'Pointillé'), ('tirets', 'Tirets'), ('arrondi', 'Arrondi'), ('ombre', 'Ombre'), ('bord_gauche', 'Bord gauche'), ('bord_haut', 'Bord haut'), ('croix', 'Croisillons')], default='plein', max_length=20, verbose_name='Style de barre'),
        ),
    ]
