# Generated by Django 5.1.1 on 2026-09-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_usernotification_transform_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCongeAjustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ajout', 'Ajout'), ('retrait', 'Retrait')], default='ajout', max_length=10)),
                ('jours', models.DecimalField(decimal_places=2, help_text='Nombre de jours (toujours positif ; le sens est donné par type_mouvement)', max_digits=6)),
                ('date', models.DateField(help_text="Date de l'ajustement (année de rattachement)")),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conge_ajustements', to='api.agent')),
            ],
            options={
                'verbose_name': 'Ajustement congés agent',
                'verbose_name_plural': 'Ajustements congés agents',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
