# Generated by Django 5.1.1 on 2026-09-17 16:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_agent_conge_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En attente BDC', 'En attente BDC'), ('BDC reçus', 'BDC reçus'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Travaux non réalisés', 'Travaux non réalisés'), ('Travaux en cours', 'Travaux en cours'), ('Travaux réalisés', 'Travaux réalisés'), ('Envoyé', 'Envoyé'), ('Faire Avenant', 'Faire Avenant'), ('A facturer', 'A facturer'), ('Facturé', 'Facturé'), ('Faire TS', 'Faire TS'), ('En attente de travaux', 'En attente de travaux'), ('En Cours', 'En Cours'), ('Terminé', 'Terminé')], default='En attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='devis',
            name='tags',
            field=models.JSONField(blank=True, default=api.models.default_devis_tags),
        ),
    ]
