# Generated by Django 5.1.1 on 2026-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_boncommande_heure_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_fin_contrat',
            field=models.DateField(blank=True, help_text='Date de fin du contrat (CDD) ou date de sortie (CDI)', null=True),
        ),
        migrations.AlterField(
            model_name='agentcontrat',
            name='date_fin_contrat',
            field=models.DateField(blank=True, help_text='Date de fin du CDD, ou date de sortie si CDI', null=True),
        ),
    ]
