# Generated by Django 5.1.1 on 2026-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_alter_agent_date_fin_contrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumeroCompteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de numéro de document',
                'verbose_name_plural': 'Compteurs de numéros de document',
                'constraints': [models.UniqueConstraint(fields=('serie', 'annee'), name='uniq_document_numero_compteur_serie_annee')],
            },
        ),
    ]
