# Generated by Django 5.1.1 on 2026-10-05 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_stock_sortie_nature_et_produit_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockloss',
            name='date_perte',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date de la sortie'),
        ),
        migrations.AlterField(
            model_name='stockloss',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Coût d'achat des unités sorties (FIFO), jamais le prix de vente", max_digits=10),
        ),
    ]
