# Generated by Django 5.2.dev20240702005204 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('phone_Number', models.IntegerField()),
                ('taux_Horaire', models.FloatField()),
                ('conge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_name', models.CharField(max_length=25, unique=True)),
                ('client_name', models.CharField(max_length=25)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('chiffre_affaire', models.FloatField(null=True)),
                ('nombre_devis', models.IntegerField(null=True)),
                ('nombre_facture', models.IntegerField(null=True)),
                ('state_chantier', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=100)),
                ('cout_materiel', models.FloatField(null=True)),
                ('cout_main_oeuvre', models.FloatField(null=True)),
                ('cout_sous_traitance', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('client_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('num_facture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=200)),
                ('Fournisseur_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
                ('description_fournisseur', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_produit', models.CharField(max_length=25)),
                ('description_produit', models.CharField(max_length=250)),
                ('price_ht', models.FloatField()),
                ('name_fournisseur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_quitus', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
    ]
