# Generated by Django 5.2.dev20240702005204 on 2024-09-23 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('phone_Number', models.IntegerField()),
                ('taux_Horaire', models.FloatField()),
                ('conge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_name', models.CharField(max_length=25, unique=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('chiffre_affaire', models.FloatField(null=True)),
                ('state_chantier', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('cout_materiel', models.FloatField(null=True)),
                ('cout_main_oeuvre', models.FloatField(null=True)),
                ('cout_sous_traitance', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('client_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=200)),
                ('Fournisseur_mail', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
                ('description_fournisseur', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_produit', models.CharField(max_length=25)),
                ('description_produit', models.CharField(max_length=250)),
                ('price_ht', models.FloatField()),
                ('name_fournisseur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='DEV-0001', max_length=100)),
                ('type', models.CharField(choices=[('Travaux', 'Travaux')], default='Travaux', max_length=20)),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('state', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('amount_facturé', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='devis', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('state_facture', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('num_bon_commande', models.CharField(max_length=100, null=True)),
                ('num_facture', models.CharField(max_length=100)),
                ('amount_facturé', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='factures', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures_travail', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.agent')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_quitus', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours'), ('Facturé', 'Facturé')], default='En Cours', max_length=20)),
                ('description_quitus', models.CharField(max_length=250)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quitus', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='quitus', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('chantier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='api.chantier')),
                ('client', models.ManyToManyField(blank=True, related_name='situations', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=25)),
                ('ville_societe', models.CharField(max_length=100)),
                ('rue_societe', models.CharField(max_length=100)),
                ('codepostal_societe', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_codepostal', message='Le code postal doit être exactement 5 chiffres.', regex='^\\d{5}$')])),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='api.societe'),
        ),
        migrations.CreateModel(
            name='SousPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties', to='api.partie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sous_partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.souspartie')),
            ],
        ),
        migrations.CreateModel(
            name='DevisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.devis')),
                ('sous_partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.souspartie')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(default='', max_length=50, unique=True)),
                ('nom_materiel', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_unitaire', models.FloatField(default='')),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('quantite_entree', models.PositiveIntegerField(default=0)),
                ('quantite_sortie', models.PositiveIntegerField(default=0)),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.chantier')),
            ],
        ),
    ]
