# Generated by Django 5.1 on 2024-08-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='souspartie',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='souspartie',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='partie',
            name='titre',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='souspartie',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='souspartie',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_parties', to='api.partie'),
        ),
    ]
