# Generated by Django 5.2.dev20240702005204 on 2024-09-24 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=50)),
                ('nom_materiel', models.CharField(max_length=50)),
                ('quantite_changee', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_mouvement', models.CharField(choices=[('entrée', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chantier')),
            ],
        ),
    ]
