# Generated by Django 5.1 on 2024-08-31 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_partie_description_remove_partie_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=10)),
                ('sous_partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_details', to='api.souspartie')),
            ],
        ),
    ]
