# Generated by Django 5.2.dev20240702005204 on 2024-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stockmovement_delete_historiquestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prix_unitaire',
            field=models.FloatField(default=0),
        ),
    ]
