# Generated by Django 5.1 on 2024-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lignedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souspartie',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
