# Generated by Django 5.1 on 2024-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_souspartie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedetail',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
