# Generated by Django 5.2.dev20240702005204 on 2024-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_stock_date_entree_remove_stock_date_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_entree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_sortie',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
